# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_hotel = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_hotel.setGeometry(QtCore.QRect(40, 100, 1051, 211))
        self.tableWidget_hotel.setObjectName("tableWidget_hotel")
        self.tableWidget_hotel.setColumnCount(4)
        self.tableWidget_hotel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hotel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hotel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hotel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hotel.setHorizontalHeaderItem(3, item)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 20, 251, 61))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser_hotelcity = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_hotelcity.setGeometry(QtCore.QRect(40, 20, 101, 61))
        self.textBrowser_hotelcity.setObjectName("textBrowser_hotelcity")
        self.pushButton_hotel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hotel.setGeometry(QtCore.QRect(440, 20, 101, 61))
        self.pushButton_hotel.setObjectName("pushButton_hotel")
        self.lineEdit_room = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_room.setGeometry(QtCore.QRect(160, 330, 251, 41))
        self.lineEdit_room.setObjectName("lineEdit_room")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 330, 101, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_room = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_room.setGeometry(QtCore.QRect(860, 330, 101, 41))
        self.pushButton_room.setObjectName("pushButton_room")
        self.tableWidget_room = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_room.setGeometry(QtCore.QRect(40, 400, 1051, 201))
        self.tableWidget_room.setObjectName("tableWidget_room")
        self.tableWidget_room.setColumnCount(4)
        self.tableWidget_room.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_room.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_room.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_room.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_room.setHorizontalHeaderItem(3, item)
        self.plainTextEdit_res_hotel = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_res_hotel.setGeometry(QtCore.QRect(40, 630, 341, 71))
        self.plainTextEdit_res_hotel.setPlaceholderText("")
        self.plainTextEdit_res_hotel.setObjectName("plainTextEdit_res_hotel")
        self.plainTextEdit_res_room = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_res_room.setGeometry(QtCore.QRect(420, 630, 341, 71))
        self.plainTextEdit_res_room.setPlaceholderText("")
        self.plainTextEdit_res_room.setObjectName("plainTextEdit_res_room")
        self.pushButton_res = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_res.setGeometry(QtCore.QRect(780, 630, 171, 71))
        self.pushButton_res.setObjectName("pushButton_res")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(970, 630, 121, 71))
        self.pushButton_back.setObjectName("pushButton_back")
        self.dateEdit_check_in = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_check_in.setGeometry(QtCore.QRect(470, 360, 131, 31))
        self.dateEdit_check_in.setDate(QDate.currentDate())
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEdit_check_in.setFont(font)
        self.dateEdit_check_in.setObjectName("dateEdit_check_in")
        self.dateEdit_check_out = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_check_out.setGeometry(QtCore.QRect(640, 360, 141, 31))
        self.dateEdit_check_out.setDate(QDate.currentDate())
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEdit_check_out.setFont(font)
        self.dateEdit_check_out.setObjectName("dateEdit_check_out")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(470, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(640, 320, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        self.menuhotel_list = QtWidgets.QMenu(self.menubar)
        self.menuhotel_list.setObjectName("menuhotel_list")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuhotel_list.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python酒店预订系统"))
        item = self.tableWidget_hotel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "酒店ID"))
        item = self.tableWidget_hotel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "酒店名"))
        item = self.tableWidget_hotel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "酒店地址"))
        item = self.tableWidget_hotel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "酒店简介"))
        self.textBrowser_hotelcity.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">酒店所在城市</span></p></body></html>"))
        self.pushButton_hotel.setText(_translate("MainWindow", "查询"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">酒店ID</span></p></body></html>"))
        self.pushButton_room.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget_room.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "房间类型"))
        item = self.tableWidget_room.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "房间价格/日"))
        item = self.tableWidget_room.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "房间可容纳人数"))
        item = self.tableWidget_room.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "剩余房间数"))
        self.plainTextEdit_res_hotel.setPlaceholderText(_translate("MainWindow", "\n"
"输入预订酒店ID"))
        self.plainTextEdit_res_room.setPlaceholderText(_translate("MainWindow", "\n"
"输入预订房间类型"))
        self.pushButton_res.setText(_translate("MainWindow", "选好了，去预订"))
        self.pushButton_back.setText(_translate("MainWindow", "返回"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">入住日期</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">离开日期</span></p></body></html>"))
        self.menuhotel_list.setTitle(_translate("MainWindow", "hotel查询"))
