# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 852)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(710, 600, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.plainTextEdit_account = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_account.setGeometry(QtCore.QRect(310, 250, 531, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_account.setFont(font)
        self.plainTextEdit_account.setObjectName("plainTextEdit_account")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 100, 521, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(240, 600, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setObjectName("pushButton_register")
        self.plainTextEdit_password = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_password.setGeometry(QtCore.QRect(310, 420, 531, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_password.setFont(font)
        self.plainTextEdit_password.setObjectName("plainTextEdit_password")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 27))
        self.menubar.setObjectName("menubar")
        self.menuregister = QtWidgets.QMenu(self.menubar)
        self.menuregister.setObjectName("menuregister")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuregister.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python酒店管理系统"))
        self.pushButton_cancel.setText(_translate("MainWindow", "取消"))
        self.plainTextEdit_account.setPlainText(_translate("MainWindow", "请输入用户ID"))
        self.label.setText(_translate("MainWindow", "酒店预订系统"))
        self.pushButton_register.setText(_translate("MainWindow", "注册"))
        self.plainTextEdit_password.setPlainText(_translate("MainWindow", "请输入用户密码"))
        self.menuregister.setTitle(_translate("MainWindow", "register"))