# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_name.setGeometry(QtCore.QRect(180, 150, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_name.setFont(font)
        self.plainTextEdit_name.setObjectName("plainTextEdit")
        self.plainTextEdit_idNum = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_idNum.setGeometry(QtCore.QRect(180, 350, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_idNum.setFont(font)
        self.plainTextEdit_idNum.setObjectName("plainTextEdit_3")
        self.plainTextEdit_telephone = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_telephone.setGeometry(QtCore.QRect(180, 450, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_telephone.setFont(font)
        self.plainTextEdit_telephone.setObjectName("plainTextEdit_4")
        self.plainTextEdit_email = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_email.setGeometry(QtCore.QRect(180, 560, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_email.setFont(font)
        self.plainTextEdit_email.setObjectName("plainTextEdit_5")
        self.dateEdit_in = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_in.setGeometry(QtCore.QRect(640, 150, 261, 61))
        self.dateEdit_in.setDate(QDate.currentDate())
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEdit_in.setFont(font)
        self.dateEdit_in.setObjectName("dateEdit")
        self.dateEdit_out = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_out.setGeometry(QtCore.QRect(640, 250, 261, 61))
        self.dateEdit_out.setDate(QDate.currentDate())
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateEdit_out.setFont(font)
        self.dateEdit_out.setObjectName("dateEdit_2")
        self.plainTextEdit_remarks = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_remarks.setGeometry(QtCore.QRect(640, 350, 271, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_remarks.setFont(font)
        self.plainTextEdit_remarks.setObjectName("plainTextEdit_7")
        self.comboBox_sex = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_sex.setGeometry(QtCore.QRect(180, 250, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_sex.setFont(font)
        self.comboBox_sex.setObjectName("comboBox")
        self.comboBox_sex.addItem("")
        self.comboBox_sex.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(940, 150, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(940, 250, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_commit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_commit.setGeometry(QtCore.QRect(610, 630, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_commit.setFont(font)
        self.pushButton_commit.setObjectName("pushButton")
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setGeometry(QtCore.QRect(870, 630, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_2")
        self.label_hotel = QtWidgets.QLabel(self.centralwidget)
        self.label_hotel.setGeometry(QtCore.QRect(120, 30, 600, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hotel.setFont(font)
        self.label_hotel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hotel.setObjectName("label")
        self.label_room = QtWidgets.QLabel(self.centralwidget)
        self.label_room.setGeometry(QtCore.QRect(640, 30, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_room.setFont(font)
        self.label_room.setAlignment(QtCore.Qt.AlignCenter)
        self.label_room.setObjectName("label_2")
        self.comboBox_customers = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_customers.setGeometry(QtCore.QRect(180, 660, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_customers.setFont(font)
        self.comboBox_customers.setObjectName("comboBox_2")
        self.comboBox_customers.addItem("")
        for i in range(1, 4):
            self.comboBox_customers.addItem("{}".format(i))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        self.menureservation = QtWidgets.QMenu(self.menubar)
        self.menureservation.setObjectName("menureservation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menureservation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python酒店预订系统"))
        self.plainTextEdit_name.setPlaceholderText(_translate("MainWindow", "请输入姓名"))
        self.plainTextEdit_idNum.setPlaceholderText(_translate("MainWindow", "请输入身份证号"))
        self.plainTextEdit_telephone.setPlaceholderText(_translate("MainWindow", "请输入联系电话"))
        self.plainTextEdit_email.setPlaceholderText(_translate("MainWindow", "请输入邮箱地址"))
        self.plainTextEdit_remarks.setPlaceholderText(_translate("MainWindow", "备注"))
        self.comboBox_sex.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox_sex.setItemText(1, _translate("MainWindow", "女"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">入住日期</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'SimSun\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">退住日期</span></p></body></html>"))
        self.label_hotel.setText(_translate("MainWindow", "TextLabel"))
        self.label_room.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_commit.setText(_translate("MainWindow", "提交订单"))
        self.pushButton_cancel.setText(_translate("MainWindow", "返回查询"))
        self.comboBox_customers.setItemText(0, _translate("MainWindow", "入住人数"))
        self.menureservation.setTitle(_translate("MainWindow", "reservation"))
