# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 853)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_hotel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hotel.setGeometry(QtCore.QRect(220, 290, 211, 141))
        self.pushButton_hotel.setObjectName("pushButton_hotel")
        self.pushButton_reservation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reservation.setGeometry(QtCore.QRect(610, 290, 211, 141))
        self.pushButton_reservation.setObjectName("pushButton_reservation")
        self.pushButton_change = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_change.setGeometry(QtCore.QRect(410, 540, 211, 131))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.pushButton_change.setFont(font)
        self.pushButton_change.setObjectName("pushButton_change")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 120, 381, 141))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 130, 161, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/jqyyd/Desktop/屏幕截图 2023-06-26 230630.jpg"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 25))
        self.menubar.setObjectName("menubar")
        self.menuquery = QtWidgets.QMenu(self.menubar)
        self.menuquery.setObjectName("menuquery")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuquery.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python酒店管理系统"))
        self.pushButton_hotel.setText(_translate("MainWindow", "查酒店"))
        self.pushButton_reservation.setText(_translate("MainWindow", "查订单"))
        self.pushButton_change.setText(_translate("MainWindow", "切换账号"))
        self.label.setText(_translate("MainWindow", "酒店预定系统"))
        self.menuquery.setTitle(_translate("MainWindow", "query"))
